version: "3.8"
services:
  pdf-service:
    build: .
    container_name: pdf-processor
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_FILE_SIZE=10485760
